version: '3.1'

services:
  db:
    container_name: data
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: a0cb03f17886
      POSTGRES_USER: admin
    ports:
      - '5432:5432'
    volumes:
          - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local